import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#00B5E2",
  },
  firstView: {
    height: "48%",
    width: "100%",
  },
  logoImage: {
    height: "100%",
    width: "100%",
  },
  secondView: {
    backgroundColor: "white",
    height: "52%",
    width: "100%",
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    overflow: "hidden",
  },
  titleTxt: {
    color: "#A9A9A9",
    fontSize: 14,
    marginTop: 50,
    textAlign: "center",
  },
  registerButtonView: {
    paddingLeft: 30,
    paddingRight: 30,
    height: 40,
    width: "80%",
    backgroundColor: "#00B5E2",
    borderRadius: 18,
    flexDirection: "row",
    marginTop: 80,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 30,
    alignSelf: "center",
  },
  registerText: {
    fontSize: 20,
    color: "white",
  },
  backImage: {
    flex: 1,
    justifyContent: "center",
  },
  commonImage: {
    height: 120,
    width: 120,
    position: "absolute",
    right: 40,
    marginTop: 30,
    marginLeft: 100,
    tintColor: "#33B4F6",
  },
  commonLeftView: {
    flexDirection: "column",
    backgroundColor: "black",
  },
  subImage: {
    height: 30,
    width: 30,
    position: "absolute",
    right: 40,
    marginTop: 70,
    marginRight: 45,
    alignItems: "center",
    justifyContent: "center",
    tintColor: "#33B4F6",
  },
  checkImage: {
    height: 25,
    width: 25,
    position: "absolute",
    right: 40,
    marginTop: 40,
    marginLeft: 100,
  },
  lineImage: {
    height: 210,
    width: 1.5,
    position: "absolute",
    marginTop: 10,
    tintColor: "grey",
  },
  regiterHereTxt: {
    fontSize: 20,
    color: "black",
    textAlign: "left",
    right: 100,
    top: 170,
  },
  userText: {
    fontSize: 20,
    color: "black",
  },
  buisnessTxt: {
    fontSize: 20,
    color: "black",
    // textAlign: "left",
    // left: 10,
    // top: 160,
  },
  leftImage: {
    height: 120,
    width: 120,
    position: "absolute",
    left: 40,
    marginTop: 30,
    marginRight: 150,
    tintColor: "grey",
  },
  bagImage: {
    height: 30,
    width: 30,
    position: "absolute",
    left: 40,
    marginTop: 70,
    marginLeft: 45,
    alignItems: "center",
    justifyContent: "center",
    tintColor: "#AEAEAE",
  },
});

export default styles;
